### ISSUE TITLE
Initial TODO List

### ISSUE THREAD

**Issue by nesterone** [nesterone/vue-vega#2]
- [x] eslint config 
- [x] editor config
- [x] precommit hooks
- [x] unit test
- [x] setup CI (trigger on push/)
- [x] cover mixing with unit tests without adding new functionality
- [x] switch from mixin to plugin
- [x]  create a dist with simple standalone html example
- [x] move samples to sepatate folder (docs), src contains only plugin
- [x] create more sexy docs page
- [x]  fill with existing functionality, no new fetaures
- [x] publish to gh-pages
- [x] synch readme with docs
