### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by xmnlab** [nesterone/vue-vega#46]
@nesterone 

do you have any idea of roadmap for this project?

**Comment by xmnlab** [comment]
what is missing to release vue-vega as "final" release?

**Comment by nesterone** [comment]
Hi, @xmnlab 

I think it's about to fix:

Must Have: 

- [ ] Export the vega API #39 
- [ ] Exclude vega and vega lite libs from our js bundle #6
- [ ] console.log #43 

Nice to Have 
- [ ] Provide tooltip support #36

And 1.0.0 version would be ready to release

**Comment by nesterone** [comment]
@xmnlab 

Not sure about 
* dataset
and 
* line with point

Could you bring more info ?

I'm going to take a look at #39, #43  an #6 

I you don't I can propose you to take a look at #36

**Comment by xmnlab** [comment]
Hey @nesterone !

datasets: https://vega.github.io/vega-lite/docs/data.html#datasets
line with points mark: https://vega.github.io/vega-lite/examples/line_overlay.html

but it is already working (using spec) with the last PR merged.

here is an example using dataset and line with points:

https://vega.github.io/editor/#/url/vega-lite/N4KABBYEQCQM4GMAWBTAtgQygLmkgLvgA5zYD0ZAbigOYYB0NAlvkgK4BG9TA9mYqkxVaGALQAbFiioAmegDZ6ABnoArODwB2UADThIUBFoBmTGjjChI16JSYoA7has3XUVGYIWAzEqV7XNwcmABNWCwAWP31XAF8YsFiAgxCMfAw4FHw4ZwTrKFT00QwZFA4OAE4K+Q4MYw4Adm95GTqEMqUIhoBGEPkUJQrjFAsAbTzAl0DAqAAPC27k6bc2TIAnTQw0EdwoNm7dCeXbDHE2HbBu5SObJJvrKeODedwZJaeIPfXN7Ys9g-eHyglFO5wsciU90gdw+jyBLzAbyhK2+Wwuexkhw++RBZwuV0hHxhTzhTzmPkBZNWKA2aL+bExlOOwNBF281yJNwAugliZ9KEZNAg0mMbqS3IUsLhxcsoD90ZLiqVylUanVGs1WsZ2hxOj0+gMhiNkYkmTYoCghTwQkxNOZpSb8kZxDw1rlsTNTChxCF6ajfmagfgAJ5EdGaHhoW2nKCO6GBmb4Hg8cT4JhEUUe1wyrPQL0+v00+VY3OJ0PhyPR8Sx0vxuPZ+uy-O+3a4sEJj1QENhv4ARzYGE0afSaeoNdriUbXI75oRObJzb+8xn0y75b7A6HLDSTDHjb52KgwfdE6gi9brJLtbXPd2-cHw53e9z8SJM-cKE8+AWAFZ-CaoEwNYAGsT07IgeFtb9cHwNZzhXAxu3RSRNGNN8AMycQUAQNMtDAw9MOwpM1iUboKnw3MoA4W0W2gRBThQHIELcS0jBtO0clwcYJ1nK8eOgY9G2sachMQ9ddigmlcXHD1XyeA9V2HLC-mQDA1m-d9gjCJBImiaY5IgHlYiAA

**Comment by xmnlab** [comment]
> console.log #43

it seems #44 has already fixed that!

**Comment by Codermar** [comment]
Hi, great project but I wonder what is going on with it. The last PR was merged 8 months ago... Any updates?

**Comment by fpompermaier** [comment]
Any news @nesterone ..?
